name: Auto Update Charts

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  update-music:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Libraries
        run: |
          npm init -y
          npm install axios cheerio

      - name: Run Fetching Script
        run: node crawler.js

      - name: Commit and Push changes
        run: |
          git config --global user.name "ChartBot"
          git config --global user.email "bot@github.com"
          git add live-data.json
          git commit -m "Cập nhật dữ liệu [Skip CI]" || exit 0
          git push
